version: '2'
services:
    projectsharing-app:
        image: projectsharing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://projectsharing-mysql:3306/projectsharing?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projectsharing-mysql:
        extends:
            file: mysql.yml
            service: projectsharing-mysql
